apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8swf
  labels:
    app.kubernetes.io/name: k8swf
    kubernetes.azure.com/generator: draft
  namespace: k8snamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8swf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8swf
    spec:
      containers:
        - name: k8swf
          image: k8srgy.azurecr.io/k8srgyimage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: "250"
              memory: "100"
            limits:
              cpu: "256"
              memory: "200"
          envFrom:
            - configMapRef:
                name: k8swf-config
            - secretRef:
                name: secret-ref
                optional: true
          livenessProbe:
            tcpSocket:
              port: 8083
          readinessProbe:
            tcpSocket:
              port: 8083
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
          startupProbe:
            tcpSocket:
              port: 8083
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
                - SYS_PTRACE
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: k8swf
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: k8swf
