apiVersion: apps/v1
kind: Deployment
metadata:
  name: dentalsurgeryapp-deployment
  labels:
    app: dentalsurgeryapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dentalsurgeryapp
  template:
    metadata:
      labels:
        app: dentalsurgeryapp
    spec:
      containers:
        - name: dentalsurgeryapp
          image: dentalsurgeryapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      # Optional service account, tolerations, nodeSelector can be added here
