name: Build and Deploy to AKS

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: dentalsurgery-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
	distribution: 'temurin'

    - name: Build JAR
      run: mvn clean package -DskipTests

    - name: Log in to Azure using personal credentials
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
        echo $AZURE_PASSWORD | az login -u $AZURE_USERNAME --password -
        az account set --subscription $AZURE_SUBSCRIPTION_ID

    - name: Log in to ACR
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        ACR_NAME: ${{ secrets.ACR_NAME }}
      run: |
        az acr login --name $ACR_NAME

    - name: Build and push Docker image
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

    - name: Set AKS context
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
        AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
      run: |
        echo $AZURE_PASSWORD | az login -u $AZURE_USERNAME --password -
        az account set --subscription $AZURE_SUBSCRIPTION_ID
        az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
